### ISSUE TITLE
Module build failed: Error: ENOENT: no such file or directory, scandir '*node_modules/node-sass/vendor'

### ISSUE THREAD

**Issue by nullp0tr** [Neufund/generic-ico#55]
both npm & yarn don't properly install node-sass when it's part of a bigger installation and don't create a vendor folder.

`npm rebuild node-sass` is required after running `yarn`.

**Comment by banciur** [comment]
@nullp0tr hey could you write more about your environment. I just tested it on mine. I cleared project `node_modules` and I don't have `node-sass` installed globally -  after running `yarn` it is working without problems.

I don't remember exactly but at some other project I had some issues with with sass after I upgraded npm or node to never version. Maybe it is the case.

**Comment by nullp0tr** [comment]
Thanks for the reply and sorry for the delayed answer.

`npm 3.10.10`
`nodejs v6.11.0`
`yarn 0.24.6`

I don't have node-sass installed globally either, but I also started running into the problem after upgrading either npm or nodejs, not sure from which version/versions anymore. I figured I'd put this here in case anybody runs into the same problem, or in case you wanna add it to the readme.

**Comment by banciur** [comment]
Thank you I will add info to our readme.

**Comment by nullp0tr** [comment]
welcome!
